apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jilja4zq1-go-gitops
  description: This is GitOps manifest for jilja4zq1-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=jilja4zq1-go
    backstage.io/kubernetes-id: jilja4zq1-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: jilja4zq1-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jilja4zq1-go
